# ~/.config/starship.toml

[username]
style_user = "grey bold"
style_root = "black bold"
format = "[$user](https://www.notion.so/kchs/$style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false